version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 074416822474.dkr.ecr.ap-southeast-1.amazonaws.com

  build:
    commands:
      - docker build -t credit-bureau-pipeline .
      - docker tag credit-bureau-pipeline:latest 074416822474.dkr.ecr.ap-southeast-1.amazonaws.com/credit-bureau-pipeline:latest

  post_build:
    commands:
      - docker push 074416822474.dkr.ecr.ap-southeast-1.amazonaws.com/credit-bureau-pipeline:latest
      - aws lambda update-function-code --function-name credit-bureau-pipeline --image-uri 074416822474.dkr.ecr.ap-southeast-1.amazonaws.com/credit-bureau-pipeline:latest --region ap-southeast-1 