name: CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
        


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Debug — show working directory
        run: |
          pwd
          ls -la
                        

      - name: Install dependencies
        run: pip install -r requirements_dev.txt

      #- name: Run flake8
      #  run: flake8 .
      
      - name: Type check
        run: mypy validate.py anonymize.py deidentify.py
        working-directory: transform

      - name: Run tests
        run: pytest -v